
#ifndef __TEST_EXT_AMF_H__
#define __TEST_EXT_AMF_H__

// >>>>>> Generated by idl.php. Do NOT modify. <<<<<<

#include <test/test_cpp_ext.h>

///////////////////////////////////////////////////////////////////////////////

class TestExtAmf : public TestCppExt {
 public:
  virtual bool RunTests(const std::string &which);

  bool test_amf_encode();
  bool test_amf_decode();
};

///////////////////////////////////////////////////////////////////////////////

#endif // __TEST_EXT_AMF_H__
