
#ifndef __EXTPROFILE_AMF_H__
#define __EXTPROFILE_AMF_H__

// >>>>>> Generated by idl.php. Do NOT modify. <<<<<<

#include <runtime/ext/ext_amf.h>

namespace HPHP {
///////////////////////////////////////////////////////////////////////////////

inline String x_amf_encode(VRefParam var, VRefParam flag = null, VRefParam callback = null, VRefParam output = null) {
  FUNCTION_INJECTION_BUILTIN(amf_encode);
  TAINT_OBSERVER(TAINT_BIT_NONE, TAINT_BIT_NONE);
  return f_amf_encode(var, flag, callback, output);
}

inline Variant x_amf_decode(CStrRef var, VRefParam flag = null, VRefParam offset = null) {
  FUNCTION_INJECTION_BUILTIN(amf_decode);
  TAINT_OBSERVER(TAINT_BIT_NONE, TAINT_BIT_NONE);
  return f_amf_decode(var, flag, offset);
}


///////////////////////////////////////////////////////////////////////////////
}

#endif // __EXTPROFILE_AMF_H__
