
#ifndef __EXTPROFILE_IGBINARY_H__
#define __EXTPROFILE_IGBINARY_H__

// >>>>>> Generated by idl.php. Do NOT modify. <<<<<<

#include <runtime/ext/ext_igbinary.h>

namespace HPHP {
///////////////////////////////////////////////////////////////////////////////

inline String x_igbinary_serialize(CVarRef var) {
  FUNCTION_INJECTION_BUILTIN(igbinary_serialize);
  return f_igbinary_serialize(var);
}

inline Variant x_igbinary_unserialize(CStrRef str) {
  FUNCTION_INJECTION_BUILTIN(igbinary_unserialize);
  return f_igbinary_unserialize(str);
}


///////////////////////////////////////////////////////////////////////////////
}

#endif // __EXTPROFILE_IGBINARY_H__
