
#ifndef __EXT_AMF_H__
#define __EXT_AMF_H__

// >>>>>> Generated by idl.php. Do NOT modify. <<<<<<

#include <runtime/base/base_includes.h>

namespace HPHP {
///////////////////////////////////////////////////////////////////////////////

String f_amf_encode(VRefParam var, VRefParam flag = null, VRefParam callback = null, VRefParam output = null);
Variant f_amf_decode(CStrRef var, VRefParam flag = null, VRefParam offset = null);

///////////////////////////////////////////////////////////////////////////////
}

#endif // __EXT_AMF_H__
