
#ifndef __EXT_IGBINARY_H__
#define __EXT_IGBINARY_H__

// >>>>>> Generated by idl.php. Do NOT modify. <<<<<<

#include <runtime/base/base_includes.h>

namespace HPHP {
///////////////////////////////////////////////////////////////////////////////

String f_igbinary_serialize(CVarRef var);
Variant f_igbinary_unserialize(CStrRef str);

///////////////////////////////////////////////////////////////////////////////
}

#endif // __EXT_IGBINARY_H__
